import crypto from 'crypto';

/**
 * Web dashboard tokens — what proves "this URL was generated by us, for this
 * Slack user, and hasn't expired yet".
 *
 * Why HMAC and not OAuth: the dashboard is opened from Slack's Home tab where
 * we already know who the user is. Bouncing them through Slack OAuth again
 * just to read the same data would be friction for zero security gain. We
 * mint a signed token at Home-tab render time and embed it in the URL — Stripe
 * and Linear do the same. Token expires after 24h; Home tab is re-rendered
 * regularly so active users always have a fresh one.
 *
 * Why not JWT: JWT brings a dependency and a parser footgun budget we don't
 * need. The payload is 4 small fields; a manual base64url(payload).hmac
 * format is ~30 lines of code and behaves identically for our use case.
 *
 * Why derive the secret from SLACK_STATE_SECRET: avoids asking the operator
 * to set yet another env var. If you ever need to rotate dashboard tokens
 * without rotating the OAuth secret, set DASHBOARD_TOKEN_SECRET explicitly
 * and it takes precedence.
 */

const DEFAULT_TTL_MS = Number(process.env.DASHBOARD_TOKEN_TTL_MS ?? `${24 * 60 * 60 * 1000}`);

function getSecret(): string {
  const explicit = process.env.DASHBOARD_TOKEN_SECRET;
  if (explicit && explicit.length >= 16) return explicit;

  const upstream = process.env.SLACK_STATE_SECRET;
  if (!upstream || upstream.length < 16) {
    throw new Error(
      'Dashboard tokens need a secret — set DASHBOARD_TOKEN_SECRET, or ensure SLACK_STATE_SECRET is set (>=16 chars).'
    );
  }
  // Domain-separate from the OAuth state secret so a token forged with one
  // can't be replayed as the other.
  return crypto.createHmac('sha256', upstream).update('aiptima/dashboard/v1').digest('hex');
}

export type DashboardTokenPayload = {
  /** Slack user id of the dashboard owner (the person who opened it). */
  uid: string;
  /** Slack team id, or null for Enterprise Grid org installs. */
  tid: string | null;
  /** Enterprise id when applicable. */
  eid: string | null;
  /** Unix ms expiry. */
  exp: number;
};

function base64urlEncode(buf: Buffer): string {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
function base64urlDecode(s: string): Buffer {
  const pad = s.length % 4 === 0 ? '' : '='.repeat(4 - (s.length % 4));
  return Buffer.from(s.replace(/-/g, '+').replace(/_/g, '/') + pad, 'base64');
}

/**
 * Mint a token for a Slack user. Call once per Home-tab render; embed the
 * resulting string in the dashboard URL.
 */
export function signDashboardToken(args: {
  userId: string;
  teamId: string | null;
  enterpriseId: string | null;
  ttlMs?: number;
}): string {
  const payload: DashboardTokenPayload = {
    uid: args.userId,
    tid: args.teamId,
    eid: args.enterpriseId,
    exp: Date.now() + (args.ttlMs ?? DEFAULT_TTL_MS),
  };
  const body = base64urlEncode(Buffer.from(JSON.stringify(payload), 'utf8'));
  const sig = base64urlEncode(
    crypto.createHmac('sha256', getSecret()).update(body).digest()
  );
  return `${body}.${sig}`;
}

export type VerifyResult =
  | { ok: true; payload: DashboardTokenPayload }
  | { ok: false; reason: 'malformed' | 'bad_signature' | 'expired' };

/**
 * Verify a token from a `?token=...` URL query. Returns the payload if valid,
 * or a typed reason otherwise. Uses constant-time comparison to avoid timing
 * leaks on the signature.
 */
export function verifyDashboardToken(token: string | undefined | null): VerifyResult {
  if (!token || typeof token !== 'string' || !token.includes('.')) {
    return { ok: false, reason: 'malformed' };
  }
  const [body, sig] = token.split('.', 2);
  if (!body || !sig) return { ok: false, reason: 'malformed' };

  let expected: Buffer;
  try {
    expected = crypto.createHmac('sha256', getSecret()).update(body).digest();
  } catch {
    return { ok: false, reason: 'bad_signature' };
  }

  let provided: Buffer;
  try {
    provided = base64urlDecode(sig);
  } catch {
    return { ok: false, reason: 'malformed' };
  }
  if (provided.length !== expected.length) return { ok: false, reason: 'bad_signature' };
  if (!crypto.timingSafeEqual(provided, expected)) return { ok: false, reason: 'bad_signature' };

  let payload: DashboardTokenPayload;
  try {
    payload = JSON.parse(base64urlDecode(body).toString('utf8'));
  } catch {
    return { ok: false, reason: 'malformed' };
  }

  if (!payload.uid || typeof payload.exp !== 'number') return { ok: false, reason: 'malformed' };
  if (payload.exp < Date.now()) return { ok: false, reason: 'expired' };

  return { ok: true, payload };
}
